# Generated by Django 4.2.16 on 2026-05-28 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("blocked", "Bloqué"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro national"
                    ),
                ),
                ("emergency_contact", models.CharField(blank=True, max_length=100)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Head",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "head_number",
                    models.PositiveIntegerField(verbose_name="Numéro de tête"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=50, verbose_name="Libellé"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("served", "Servie"),
                            ("suspended", "Suspendue"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heads",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tête",
                "verbose_name_plural": "Têtes",
                "ordering": ["member", "head_number"],
                "unique_together": {("member", "head_number")},
            },
        ),
    ]
