# Generated by Django 4.2.16 on 2026-05-28 07:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("cycles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant dû"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Espèces"),
                            ("bank_transfer", "Virement bancaire"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payment_proofs/",
                        verbose_name="Preuve de paiement",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Payée"),
                            ("late", "En retard"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de soumission"
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="cycles.cycle",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="members.head",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributions_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
                "ordering": ["-created_at"],
                "unique_together": {("head", "cycle")},
            },
        ),
    ]
