# Generated by Django 4.2.16 on 2026-05-28 07:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom du cycle")),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "contribution_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant par tête"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0200"),
                        max_digits=5,
                        verbose_name="Taux de commission (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("open", "Ouvert - Contributions"),
                            ("distribution", "Distribution en cours"),
                            ("closed", "Clôturé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cycles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cycle",
                "verbose_name_plural": "Cycles",
                "ordering": ["-start_date"],
            },
        ),
    ]
