# Generated by Django 4.2.16 on 2026-05-28 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cycles", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emergency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif de l'urgence")),
                (
                    "justification_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="emergency_docs/",
                        verbose_name="Document justificatif",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("refused", "Refusée"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_notes",
                    models.TextField(blank=True, verbose_name="Notes de décision"),
                ),
                (
                    "new_position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nouvelle position assignée"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergencies",
                        to="cycles.cycle",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergencies_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergencies",
                        to="members.head",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergencies",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Urgence",
                "verbose_name_plural": "Urgences",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="emergency",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "approved"])),
                fields=("member", "cycle"),
                name="unique_active_emergency_per_cycle",
            ),
        ),
    ]
