# Generated by Django 4.2.16 on 2026-05-28 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("cycles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RotationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        verbose_name="Position dans la rotation"
                    ),
                ),
                (
                    "original_position",
                    models.PositiveIntegerField(verbose_name="Position originale"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("served", "Servi"),
                            ("skipped", "Ignoré"),
                            ("postponed", "Reporté"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("is_emergency", models.BooleanField(default=False)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotation_orders",
                        to="cycles.cycle",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotation_orders",
                        to="members.head",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordre de rotation",
                "verbose_name_plural": "Ordres de rotation",
                "ordering": ["cycle", "position"],
                "unique_together": {("cycle", "head")},
            },
        ),
        migrations.CreateModel(
            name="RotationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Création"),
                            ("modified", "Modification"),
                            ("emergency", "Urgence"),
                            ("postponed", "Report"),
                            ("restored", "Restauration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "previous_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("new_position", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rotation_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="rotation.rotationorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de rotation",
                "verbose_name_plural": "Historiques de rotation",
                "ordering": ["-changed_at"],
            },
        ),
    ]
